version: '3.8'
services:
  influxdb:
    image: influxdb
    container_name: influxdb
    hostname: influxdb
    restart: unless-stopped
    volumes:
      - "/srv/containers/influxdb/data:/var/lib/influxdb2"
    ports:
      - 8086:8086
    networks:
      - mosquitto-net

  telegraf:
    image: telegraf
    hostname: telegraf
    container_name: telegraf
    volumes:
    - "/srv/containers/influxdb/telegraf/etc/telegraf.conf:/etc/telegraf/telegraf.conf"
    depends_on:
      - influxdb
    links:
      - influxdb
    ports:
      - 8125:8125/udp
    networks:
      - mosquitto-net
networks:
  mosquitto-net:
    name: mosquitto
    external: true
